phil = User.create(username: "Dr. Phil", password: "pw", uid: "abc123")
dre = User.create(username: "Dr. Dre", password: "pw", uid: "def456")
mike = User.create(username: "Dr. Mike", password: "pw", uid:"ghi789")
house = User.create(username: "Dr. House", password: "pw", uid:"jkl012")
doom = User.create(username: "Dr. Doom", password: "pw", uid:"mno345")

ny = Office.create(state: "New York", city: "NYC")
nj = Office.create(state: "New Jersey", city: "Patterson") 
fl = Office.create(state: "Florida", city: "Miami")
tx = Office.create(state: "Texas", city: "Dallas")
ca = Office.create(state: "California", city: "San Jose")

# vivian = Patient.create(name: "Vivian", diagnosis: "sprained neck", user_id: phil.id, office_id: ny.id)
# hilary = Patient.create(name: "Hilary", diagnosis: "spoiled", user_id: dre.id, office_id: nj.id)
# jeffrey = Patient.create(name: "Jeffrey", diagnosis: "overworked", user_id: mike.id, office_id: fl.id)
# carlton = Patient.create(name: "Carlton", diagnosis: "vertically challenged", user_id: house.id, office_id: tx.id)
# ashley = Patient.create(name: "Ashley ", diagnosis: "youngest", user_id: doom.id, office_id: ca.id)
# ted = Patient.create(name: "Ted", diagnosis: "forever single", user_id: phil.id, office_id: ny.id)
# marshall = Patient.create(name: "Marshall", diagnosis: "tall", user_id: dre.id, office_id: nj.id)
# lily = Patient.create(name: "Lily", diagnosis: "spendthrifter", user_id: mike.id, office_id: fl.id)
# barney = Patient.create(name: "Barney", diagnosis: "womanizer", user_id: house.id, office_id: tx.id)
# robin = Patient.create(name: "Robin", diagnosis: "reporter", user_id: doom.id, office_id: ca.id)

# Exercise.create(name: "Push ups", reps: 5, patient_id: vivian.id)
# Exercise.create(name: "Pull ups", reps: 10, patient_id: hilary.id)
# Exercise.create(name: "Rows", reps: 15, patient_id: jeffrey.id)
# Exercise.create(name: "Foam Rolling", reps: 20, patient_id: carlton.id)
# Exercise.create(name: "Banded Rotations", reps: 25, patient_id: ashley.id)
# Exercise.create(name: "Bird Dog", reps: 30, patient_id: ted.id)
# Exercise.create(name: "Alphabets", reps: 35, patient_id: marshall.id)
# Exercise.create(name: "Towel Scrunch", reps: 40, patient_id: lily.id)
# Exercise.create(name: "Piriformis Stretch", reps: 45, patient_id: barney.id)
# Exercise.create(name: "Hamstring Stretch", reps: 50, patient_id: robin.id)
# Exercise.create(name: "Standing Hip Flexor", reps: 5, patient_id: vivian.id)
# Exercise.create(name: "Straight Leg Raise", reps: 10, patient_id: hilary.id)
# Exercise.create(name: "Bridge", reps: 15, patient_id: jeffrey.id)
# Exercise.create(name: "Cross Hearts", reps: 20, patient_id: carlton.id)
# Exercise.create(name: "Clamshells", reps: 25, patient_id: ashley.id)
# Exercise.create(name: "Cervical Retraction", reps: 30, patient_id: ted.id)
# Exercise.create(name: "Thoracic Extension", reps: 35, patient_id: marshall.id)
# Exercise.create(name: "Lumbar Extension", reps: 40, patient_id: lily.id)
# Exercise.create(name: "Sprints", reps: 45, patient_id: barney.id)
# Exercise.create(name: "Banded Sprints", reps: 50, patient_id: robin.id)


